server:
  port: 8081

spring:
  config:
    activate:
      on-profile: auth-service

  datasource:
    name: auth-service
    url: jdbc:h2:mem:bybud_auth
    username: root
    password: password
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

bybud:
  app:
    jwtSecret: auth-secret
    jwtRefreshSecret: auth-refresh-secret
    jwtExpirationMs: 86400000
    jwtRefreshExpirationMs: 172800000


