server:
  port: 8083

spring:
  config:
    activate:
      on-profile: user-service

  datasource:
    name: user-service
    url: jdbc:h2:mem:bybud_user
    username: root
    password: password
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: DEBUG

