# common/application.yml


bybud:
  app:
    jwtSecret: R9uvesizQpPFmDWcFGmoB0RIpN84cEWLzwE5GjAOyfE=
    jwtRefreshSecret: R9uvesizQpPFmDWcFGmoB0RIpN84cEWLzwE5GjAOyfE@abcdefgh1234567890
    jwtExpirationMs: 86400000
    jwtRefreshExpirationMs: 8640000
