server:
  port: 8082
  delivery-service-specific-property: value

spring:
  config:
    activate:
      on-profile: delivery-service

  datasource:
    name: delivery-service
    url: jdbc:h2:mem:bybud_delivery
    username: root
    password: password
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

bybud:
  app:
    jwtSecret: R9uvesizQpPFmDWcFGmoB0RIpN84cEWLzwE5GjAOyfE=
    jwtRefreshSecret: R9uvesizQpPFmDWcFGmoB0RIpN84cEWLzwE5GjAOyfE@abcdefgh1234567890
    jwtExpirationMs: 86400000
    jwtRefreshExpirationMs: 8640000

logging:
  level:
    root: DEBUG
